<?php
return [
    ['label' => 'United States - English', 'hl' => 'en', 'gl' => 'US'],
    ['label' => 'United Kingdom - English', 'hl' => 'en', 'gl' => 'GB'],
    ['label' => 'Canada - English', 'hl' => 'en', 'gl' => 'CA'],
    ['label' => 'Canada - French', 'hl' => 'fr', 'gl' => 'CA'],
    ['label' => 'Australia - English', 'hl' => 'en', 'gl' => 'AU'],
    ['label' => 'Germany - German', 'hl' => 'de', 'gl' => 'DE'],
    ['label' => 'France - French', 'hl' => 'fr', 'gl' => 'FR'],
    ['label' => 'Spain - Spanish', 'hl' => 'es', 'gl' => 'ES'],
    ['label' => 'Mexico - Spanish', 'hl' => 'es', 'gl' => 'MX'],
    ['label' => 'Brazil - Portuguese', 'hl' => 'pt', 'gl' => 'BR'],
    ['label' => 'Portugal - Portuguese', 'hl' => 'pt', 'gl' => 'PT'],
    ['label' => 'Italy - Italian', 'hl' => 'it', 'gl' => 'IT'],
    ['label' => 'Netherlands - Dutch', 'hl' => 'nl', 'gl' => 'NL'],
    ['label' => 'Japan - Japanese', 'hl' => 'ja', 'gl' => 'JP'],
    ['label' => 'India - English', 'hl' => 'en', 'gl' => 'IN'],
    ['label' => 'India - Hindi', 'hl' => 'hi', 'gl' => 'IN'],
    ['label' => 'Argentina - Spanish', 'hl' => 'es', 'gl' => 'AR'],
    ['label' => 'Colombia - Spanish', 'hl' => 'es', 'gl' => 'CO'],
    ['label' => 'Chile - Spanish', 'hl' => 'es', 'gl' => 'CL'],
    ['label' => 'Peru - Spanish', 'hl' => 'es', 'gl' => 'PE'],
    ['label' => 'Switzerland - German', 'hl' => 'de', 'gl' => 'CH'],
    ['label' => 'Switzerland - French', 'hl' => 'fr', 'gl' => 'CH'],
    ['label' => 'Switzerland - Italian', 'hl' => 'it', 'gl' => 'CH'],
    ['label' => 'Belgium - Dutch', 'hl' => 'nl', 'gl' => 'BE'],
    ['label' => 'Belgium - French', 'hl' => 'fr', 'gl' => 'BE'],
    ['label' => 'Sweden - Swedish', 'hl' => 'sv', 'gl' => 'SE'],
    ['label' => 'Norway - Norwegian', 'hl' => 'no', 'gl' => 'NO'],
    ['label' => 'Denmark - Danish', 'hl' => 'da', 'gl' => 'DK'],
    ['label' => 'Finland - Finnish', 'hl' => 'fi', 'gl' => 'FI'],
    ['label' => 'Poland - Polish', 'hl' => 'pl', 'gl' => 'PL'],
    ['label' => 'Russia - Russian', 'hl' => 'ru', 'gl' => 'RU'],
    ['label' => 'Turkey - Turkish', 'hl' => 'tr', 'gl' => 'TR'],
    ['label' => 'South Korea - Korean', 'hl' => 'ko', 'gl' => 'KR'],
    ['label' => 'China - Chinese (Simplified)', 'hl' => 'zh-CN', 'gl' => 'CN'],
    ['label' => 'Taiwan - Chinese (Traditional)', 'hl' => 'zh-TW', 'gl' => 'TW'],
    ['label' => 'Hong Kong - Chinese (Traditional)', 'hl' => 'zh-TW', 'gl' => 'HK'],
    ['label' => 'Singapore - English', 'hl' => 'en', 'gl' => 'SG'],
    ['label' => 'Malaysia - Malay', 'hl' => 'ms', 'gl' => 'MY'],
    ['label' => 'Indonesia - Indonesian', 'hl' => 'id', 'gl' => 'ID'],
    ['label' => 'Thailand - Thai', 'hl' => 'th', 'gl' => 'TH'],
    ['label' => 'Vietnam - Vietnamese', 'hl' => 'vi', 'gl' => 'VN'],
    ['label' => 'Philippines - English', 'hl' => 'en', 'gl' => 'PH'],
    ['label' => 'South Africa - English', 'hl' => 'en', 'gl' => 'ZA'],
    ['label' => 'Nigeria - English', 'hl' => 'en', 'gl' => 'NG'],
    ['label' => 'Kenya - English', 'hl' => 'en', 'gl' => 'KE'],
    ['label' => 'Egypt - Arabic', 'hl' => 'ar', 'gl' => 'EG'],
    ['label' => 'Saudi Arabia - Arabic', 'hl' => 'ar', 'gl' => 'SA'],
    ['label' => 'UAE - Arabic', 'hl' => 'ar', 'gl' => 'AE'],
    ['label' => 'Israel - Hebrew', 'hl' => 'iw', 'gl' => 'IL'],
    ['label' => 'Ireland - English', 'hl' => 'en', 'gl' => 'IE'],
    ['label' => 'New Zealand - English', 'hl' => 'en', 'gl' => 'NZ'],
    ['label' => 'Austria - German', 'hl' => 'de', 'gl' => 'AT'],
    ['label' => 'Czech Republic - Czech', 'hl' => 'cs', 'gl' => 'CZ'],
    ['label' => 'Hungary - Hungarian', 'hl' => 'hu', 'gl' => 'HU'],
    ['label' => 'Romania - Romanian', 'hl' => 'ro', 'gl' => 'RO'],
    ['label' => 'Ukraine - Ukrainian', 'hl' => 'uk', 'gl' => 'UA'],
    ['label' => 'Greece - Greek', 'hl' => 'el', 'gl' => 'GR'],
];
