title: Site

columns:
  top:
    width: 1/1
    sections:
      stats:
        label: Stats

  left:
    width: 1/3
    sections:
      pages:
        type: pages
        label: Menu links

  middle:
    width: 1/3
    sections:
      info:

  right:
    width: 1/3
    sections:
      pages:
        label: Trending posts

  bottom:
    width: 1/1
