title: Site

columns:
  top:
    width: 1/1
    sections:
      stats:
        label: Stats
        type: stats
        # Available size options: small, medium, large, huge. Default is large
        size: huge
        reports:
          - label:
              en: Posts
              es: Artículos
            value: 123
            link: pages/posts
            theme: positive
            icon: blog 
          - label: Landings
            value: 123
            link: pages/posts
            theme: positive
            icon: blog 

  left:
    width: 1/3
    sections:
      pages:
        type: pages
        label: Menu links

  middle:
    width: 1/3
    sections:
      info:

  right:
    width: 1/3
    sections:
      pages:
        label: Trending posts

  bottom:
    width: 1/1
