enabled: true
showchildpages:
  enabled: true
email: contacto@moonagency.net
phone: '34000000000'
address: 'C/ Madrid 00, Madrid, 28000'
info: 'Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl uekt aliquip ex ea commodo consequat duis auhtem.'
slogan: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius eligendi maiores assumenda, cumque soluta error.'
