title: 'Moon Agency'
default_lang: es
author:
  name: alv.dev
  email: soy@alv.dev
  url: 'https://alv.dev/'
  gravatar: soy@alv.dev
  description: 'Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.'
taxonomies:
  - category
  - tag
  - month
metadata:
  description: 'Moon Agency is a minimal model agency theme'
summary:
  enabled: true
  format: short
  size: 100
  delimiter: '==='
  striptags: true
redirects: null
routes: null
blog:
  route: ''
description: 'Model agency'
global_featured_image: featured.jpg
social:
  -
    text: facebook
    url: 'http://www.facebook.com/alvdev'
  -
    text: twitter
    url: 'http://www.twitter.com/alvdev'
  -
    text: linkedin
    url: 'http://www.linkedin.com/alvdev'
  -
    text: youtube-play
    url: 'http://www.youtube.com/alvdev'
  -
    text: home
    url: /
menu:
  -
    url: error
    text: 'Error Page'
copyright: '<div class="legal"><a href="#" id="about-textos-legales#terminosCondiciones">Textos Legales</a><a href="#" id="about-textos-legales#politicaPrivacidad">Política Privacidad</a><a href="#" id="about-textos-legales#cookies">Cookies</a><a href="#" id="about-textos-legales#1_4_4">USC 2257</a><a href="#" id="about-contactar">Contactar</a></div><div class="site-ccards"><img class="logo_visa" src="https://alv.dev/demo/005/user/themes/receptar/images/pagovisanew.png" alt="VISA"><img class="logo_visaelectron" src="https://alv.dev/demo/005/user/themes/receptar/images/pagovisaelectronnew.png" alt="VISA Electron"><img class="logo_mastercard" src="https://alv.dev/demo/005/user/themes/receptar/images/pagomastercardnew.png" alt="MasterCard"><img class="logo_maestrocard" src="https://alv.dev/demo/005/user/themes/receptar/images/pagomaestrocardnew.png" alt="Maestro"></div>'
