extends@: default

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT
          fields:
            header.title:
              type: text
              autofocus: true

            header.subtitle:
              type: textarea
              label: DEFAULT.SUBTITLE
              style: vertical
              ordering@: header.title
              validate:
                type: textarea

            header.description:
              type: textarea
              label: DEFAULT.DESCRIPTION
              style: vertical
              ordering@: header.subtitle
              validate:
                type: textarea

            content:
              label: DEFAULT.BODY
